const express = require('express');
const controller = require('../modules/metricasv2/controllers/metricas.controller');
const authController = require('../modules/metricasv2/controllers/auth.controller');

const router = express.Router();

router.get('/auth/session', authController.session);
router.post('/auth/login', authController.login);
router.post('/auth/logout', authController.logout);
router.get('/auth/users', authController.listUsers);
router.post('/auth/users', authController.createUser);
router.patch('/auth/users/:id', authController.updateUser);
router.patch('/auth/users/:id/password', authController.updateUserPassword);
router.delete('/auth/users/:id', authController.deleteUser);
router.get('/health', controller.health);
router.get('/commissions/dashboard', controller.getCommissionsDashboard);
router.get('/commissions/person', controller.getCommissionPersonDetail);
router.get('/commissions/config', controller.getCommissionConfig);
router.post('/commissions/config', controller.saveCommissionConfig);
router.post('/commissions/config/default', controller.saveDefaultCommissionConfig);
router.post('/commissions/config/lock', controller.lockCommissionMonth);
router.get('/alertas-operativas', controller.getOperationalAlertsData);
router.get('/views', controller.getResources);
router.get('/views/:resource', controller.getResourceRows);
router.get('/kpi-closers/rules', controller.getKpiCloserRules);
router.post('/kpi-closers/rules', controller.saveKpiCloserRules);
router.get('/agenda-bonus/rules', controller.getAgendaBonusRules);
router.post('/agenda-bonus/rules', controller.saveAgendaBonusRules);
router.get('/agenda-calendar/assignments', controller.listAgendaCalendarAssignments);
router.post('/agenda-calendar/assignments', controller.saveAgendaCalendarAssignment);
router.get('/reportes/premio', controller.getReportesPremioConfig);
router.post('/reportes/premio', controller.saveReportesPremioConfig);
router.get('/reportes/comentarios', controller.listReportComments);
router.post('/reportes/comentarios', controller.createReportComment);
router.patch('/reportes/comentarios/:id/read', controller.markReportCommentRead);
router.get('/marketing/inversion', controller.getMarketingInvestment);
router.post('/marketing/inversion', controller.saveMarketingInvestment);
router.get('/marketing/inversiones', controller.listMarketingInvestments);
router.patch('/marketing/inversiones', controller.updateMarketingInvestmentRecord);
router.delete('/marketing/inversiones', controller.deleteMarketingInvestmentRecord);
router.get('/marketing/aov-dia-1', controller.getMarketingAovDia1);
router.get('/marketing/ventas-totales', controller.getMarketingVentasTotales);
router.get('/marketing/cash-collected-agenda', controller.getMarketingCashCollectedAgenda);
router.get('/marketing/campaign-totales', controller.getMarketingCampaignTotals);
router.get('/utm-builder/presets', controller.listUtmBuilderPresets);
router.post('/utm-builder/presets', controller.saveUtmBuilderPreset);
router.delete('/utm-builder/presets', controller.deleteUtmBuilderPreset);
router.get('/reportes-personales/pdf', controller.getCloserPersonalPdf);
router.post('/reportes-personales/pdf', express.raw({ type: ['application/pdf', 'application/octet-stream'], limit: '20mb' }), controller.uploadCloserPersonalPdf);
router.get('/dolar-hoy', controller.getDollarQuotes);
router.get('/comprobantes-loader/bootstrap', controller.getComprobantesLoaderBootstrap);
router.get('/comprobantes-loader/mine', controller.listMyComprobantes);
router.get('/comprobantes-loader/cliente', controller.lookupComprobantesLoaderClient);
router.get('/comprobantes-loader/venta-relacionada', controller.lookupComprobantesLoaderRelatedSale);
router.post('/comprobantes-loader', controller.createComprobanteManual);
router.post('/assistant/ask', controller.askAssistant);
router.get('/closers/personal-report', controller.getCloserPersonalReport);
router.post('/closers/personal-report', controller.generateCloserPersonalReport);

module.exports = router;
