INSERT INTO public.mercado_pago_club_workflow (
  record_kind,
  record_id,
  status,
  record_snapshot,
  reconciled_at,
  reconciled_by_email,
  invoiced_at,
  invoiced_by_email,
  arca_cae,
  arca_invoice_number,
  arca_response,
  created_at,
  updated_at
)
VALUES (
  'payment',
  '169232739558',
  'invoiced',
  '{
    "kind": "payment",
    "id": "169232739558",
    "source": "mercado_pago",
    "date": "2026-07-17T09:21:31.000-04:00",
    "createdAt": "2026-07-17T09:21:28.000-04:00",
    "description": "Plan Club del Costo - Agosto 2",
    "externalReference": "",
    "payer": "Nadia Cavallini",
    "payerEmail": "nadia.cavallini@gmail.com",
    "payerAddress": "No informado (comprobante histórico)",
    "identificationType": "CUIT",
    "identificationNumber": "27336067311",
    "amount": 15000,
    "currency": "ARS",
    "status": "approved",
    "statusDetail": "accredited",
    "paymentMethod": "debvisa",
    "subscriptionId": "",
    "requestedInvoiceType": "A",
    "vatConditionId": 6,
    "historicalArcaImport": true
  }'::jsonb,
  '2026-07-17T13:21:31.000Z'::timestamptz,
  'matirandazzo@gmail.com',
  '2026-07-17T13:21:31.000Z'::timestamptz,
  'matirandazzo@gmail.com',
  '86294313574428',
  '00005-00000001',
  '{
    "invoiceType": "A",
    "invoiceTypeCode": 1,
    "pointOfSale": 5,
    "invoiceNumber": 1,
    "cae": "86294313574428",
    "caeExpiration": "20260727",
    "issuedAt": "2026-07-17T13:21:31.000Z",
    "serviceFrom": "2026-07-01",
    "serviceTo": "2026-07-31",
    "paymentDueDate": "2026-07-17",
    "documentType": 80,
    "documentNumber": "27336067311",
    "recipientName": "Nadia Cavallini",
    "recipientAddress": "No informado (comprobante histórico)",
    "vatConditionId": 6,
    "vatCondition": "Responsable Monotributo",
    "concept": "Servicios",
    "description": "Suscripción mensual a edición digital informativa sobre costos y gestión, con contenidos originales y actualización periódica en línea - Club del Costo.",
    "taxTreatment": "Exento",
    "amounts": {
      "total": 15000,
      "net": 0,
      "exempt": 15000,
      "vat": 0,
      "vatRate": 0,
      "vatRateId": null
    },
    "legends": [
      "El crédito fiscal discriminado en el presente comprobante, sólo podrá ser computado a efectos del Régimen de Sostenimiento e Inclusión Fiscal para Pequeños Contribuyentes de la Ley N.º 27.618.",
      "Régimen de Transparencia Fiscal al Consumidor (Ley 27.743)"
    ],
    "showTransparency": true,
    "showMonotributoLegend": true,
    "amount": 15000,
    "currency": "ARS",
    "historicalImport": true
  }'::jsonb,
  '2026-07-17T13:21:31.000Z'::timestamptz,
  now()
)
ON CONFLICT (record_kind, record_id) DO NOTHING;
